### ISSUE TITLE
%save-test-to-file creates tests without result-face

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/dev-suite#31]
This results in a syntax error. 

See: https://github.com/uqbar-dao/dev-suite/blob/7372b5400c8f982f3f37cac274aedc6737a9a377/lib/zig/ziggurat.hoon#L151

**Comment by hosted-fornet** [comment]
I think this no longer happens.

**Comment by hosted-fornet** [comment]
Let me know if you still see this, otherwise, we can close the issue.
