### ISSUE TITLE
Update %pyro workflow for linedb

### ISSUE THREAD

**Issue by tadad** [uqbar-dao/dev-suite#54]
While #28 gave us quick-boot/quick-install - we've since discovered that this workflow is not the one we are going to go with.
*Old workflow*
- install on host
- copy host desk into pyro-ships

*New workflow*
- get files into your linedb
- install your desk on *one* of the fakeships
- copy the desk to all fake-ships

in particular this means getting rid of `%add-desk` in pyro, something that is mostly a temporary fix regardless

**Comment by tadad** [comment]
@hosted-fornet correct me if I am wrong here

**Comment by hosted-fornet** [comment]
Yeah, this is correct, though we may only want the desk on a subset of fakeships.

**Comment by hosted-fornet** [comment]
This is working, with some caveats like https://github.com/uqbar-dao/linedb/issues/41
