### ISSUE TITLE
vship-related scry desiderata

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/dev-suite#61]
The following information sources are needed.

1. a scry (or poke, or an update to an existing scry) to retrieve which desks are on a vship (or all vships)
2. a scry (or ditto) to retrieve which desks are `|install`ed on a vship (or all vships)
3. a scry (or ditto) for which agents are running on a vship (or would this just be a dojo poke with `+vats`?)

These don't need to be scries if the info is better retrieved in a different way.

**Comment by 0x70b1a5** [comment]
if it's feasible to represent all of this information in the `sync-desk-to-vship` scry, that may possibly be the ideal

**Comment by hosted-fornet** [comment]
Resolved by #63
